apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dm8x1m8hv-java-quarkus
  janus-idp.io/tekton: dm8x1m8hv-java-quarkus
  backstage.io/kubernetes-id: dm8x1m8hv-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dm8x1m8hv-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
